export const servicesPageServices = [
  "program Management",
  "change management",
  "agile project delivery",
  "business transformation",
  "strategic planning",
  "technology consulting",
  "SaaS platform development",
  "custom app development",
  "enterprise software",
  "UI/UX design services",
  "digital transformation",
  "cloud migration services",
  "IT modernization",
  "government digitalization",
  "business process reengineering",
] as const;

export const homepageServices = [
  "enterprise program management",
  "change management (OCM)",
  "stakeholder engagement",
  "agile coaching & PMO",
  "performance tracking",
  "web & mobile apps",
  "SaaS & CRM development",
  "cloud & API integration",
  "UI/UX design & prototyping",
  "enterprise system modernization",
  "digital strategy & roadmap",
  "business process reengineering",
  "data & analytics enablement",
  "cloud migration & modernization",
  "e-government",
] as const;
